In [3]:
import pandas as pd
lst=["faraz","ammar","alhamd","anas"]
df = pd.Series(lst,index=['a','b','c','d']) # giving index as per our choice.
print(df)
df['a']

a     faraz
b     ammar
c    alhamd
d      anas
dtype: object

'faraz'

In [4]:

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]
gd=pd.DataFrame(data,columns=["name","age"])
print(gd)

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [5]:
df=pd.read_excel("Book1.xlsx")
df

     Name   School  Marks
0  farazz      DPS     98
1    ayan      UPS     34
2   arman      APS     56
3   rehan    KAMAL     65
4   irfan      CMS     33
5  faizan  ST.MARY     89

In [6]:
df1=pd.read_csv("Book1.csv")
df1

     Name   School  Marks
0  farazz      DPS     98
1    ayan      UPS     34
2   arman      APS     56
3   rehan    KAMAL     65
4   irfan      CMS     33
5  faizan  ST.MARY     89

In [7]:
df=pd.read_json("data2.json")
df

     name language
0   faraz  pyrthon
1  arushg     java

In [8]:
df=pd.read_json("datanew.json")
df

     name language
0   faraz  pyrthon
1  arushg     java

In [9]:
df=pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [10]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df
import numpy as np
arr=np.max(df["total_bill"])
arr

50.81

In [11]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [14]:
df
import numpy as np
new=np.max(df["time"])
new

'Lunch'

In [15]:
df=pd.read_excel("movies_data.xlsx")
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,836,8.8
1,Tom Hanks,Forrest Gump,1994,Drama,703,8.8
2,Christian Bale,The Dark Knight,2008,Action,914,9.0
3,Robert Downey Jr.,Iron Man,2008,Action,611,7.9
4,Sam Worthington,Avatar,2009,Sci-Fi,2435,7.9
5,Joaquin Phoenix,Joker,2019,Drama,778,8.3
6,Keanu Reeves,The Matrix,1999,Sci-Fi,501,8.7
7,Brad Pitt,Fight Club,1999,Drama,256,8.8
8,Matthew McConaughey,Interstellar,2014,Sci-Fi,731,8.7
9,Heath Ledger,The Dark Knight,2008,Action,914,9.0
10,Margot Robbie,Barbie,2023,Comedy,1195,6.8
11,Cillian Murphy,Oppenheimer,2023,Biography,830,8.6

In [16]:
df["Actor"]

0       Leonardo DiCaprio
1               Tom Hanks
2          Christian Bale
3       Robert Downey Jr.
4         Sam Worthington
5         Joaquin Phoenix
6            Keanu Reeves
7               Brad Pitt
8     Matthew McConaughey
9            Heath Ledger
10          Margot Robbie
11         Cillian Murphy
Name: Actor, dtype: object

In [17]:
df[["Actor","IMDb"]]

                  Actor  IMDb
0     Leonardo DiCaprio   8.8
1             Tom Hanks   8.8
2        Christian Bale   9.0
3     Robert Downey Jr.   7.9
4       Sam Worthington   7.9
5       Joaquin Phoenix   8.3
6          Keanu Reeves   8.7
7             Brad Pitt   8.8
8   Matthew McConaughey   8.7
9          Heath Ledger   9.0
10        Margot Robbie   6.8
11       Cillian Murphy   8.6

In [18]:
df.loc[1] # return the whole row 1 with all values.....

Actor                       Tom Hanks
Film                     Forrest Gump
Year                             1994
Genre                           Drama
BoxOffice (INR Crore)             703
IMDb                              8.8
Name: 1, dtype: object

In [19]:
df.loc[0:5,"Genre"]

0    Sci-Fi
1     Drama
2    Action
3    Action
4    Sci-Fi
5     Drama
Name: Genre, dtype: object

In [20]:
df.loc[0,"Actor"]

'Leonardo DiCaprio'

In [21]:
df.at[0,"Actor"] #  .at[] is specified for accessing only a particular element...

'Leonardo DiCaprio'

In [22]:
df.iat[0,0]

'Leonardo DiCaprio'

In [23]:
df[df["IMDb"]>8.6]["Actor"] # give me the name of those actors whose movies IMDb rating is greater than 8.6

0      Leonardo DiCaprio
1              Tom Hanks
2         Christian Bale
6           Keanu Reeves
7              Brad Pitt
8    Matthew McConaughey
9           Heath Ledger
Name: Actor, dtype: object

In [24]:
df[(df["Year"]>2018) & (df["IMDb"]>8.5)]

             Actor         Film  Year      Genre  BoxOffice (INR Crore)  IMDb
11  Cillian Murphy  Oppenheimer  2023  Biography                    830   8.6

## df.query is much more efficient and easy to use as compared to df[df[""]]

In [25]:
df.query("IMDb > 8.5 and Year > 2018")

             Actor         Film  Year      Genre  BoxOffice (INR Crore)  IMDb
11  Cillian Murphy  Oppenheimer  2023  Biography                    830   8.6

In [26]:
df.query("Actor == 'Cillian Murphy'")

             Actor         Film  Year      Genre  BoxOffice (INR Crore)  IMDb
11  Cillian Murphy  Oppenheimer  2023  Biography                    830   8.6

In [27]:
df.query("2002 <Year<=2017") # chaining
# df.query("Year >2002 and Year <2017") both have same work

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,836,8.8
2,Christian Bale,The Dark Knight,2008,Action,914,9.0
3,Robert Downey Jr.,Iron Man,2008,Action,611,7.9
4,Sam Worthington,Avatar,2009,Sci-Fi,2435,7.9
8,Matthew McConaughey,Interstellar,2014,Sci-Fi,731,8.7
9,Heath Ledger,The Dark Knight,2008,Action,914,9.0

In [28]:
df=pd.read_csv("data_cleaning_sample.csv")

In [29]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [30]:
df.isnull()
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [31]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [32]:
df1=df.duplicated().copy()

In [33]:
df1

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [34]:
df.fillna('hugdiya')

      Name      Age         City Gender              Email   Join Date
0    Alice     25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  hugdiya        Delhi      M    charlie@example  20-07-2021
2      Bob     30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  hugdiya        Delhi      M    charlie@example  20-07-2021
4    David     22.0       Mumbai      M  david@example.com  12-11-2019
5  hugdiya     28.0        Delhi      F     eve@domain.com     hugdiya
6    Alice     25.0     New York      F  alice@example.com  01-05-2021
7    Alice     25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  hugdiya        Delhi      M    charlie@example  20-07-2021

In [35]:

df2=df["Age"].fillna(df["Age"].mean())

In [36]:
df2

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [37]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [38]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [39]:
df2=df.drop_duplicates()
df2
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [40]:
df2["Name"].str.lower()
dfx=df2.replace('Delhi','dariyapur')
dfx

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN    dariyapur      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0    dariyapur      F     eve@domain.com         NaN

In [41]:
dfz=df.dropna().copy()

In [42]:
dfz

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [43]:
dfz["Age"]=dfz["Age"].astype(int)
dfz

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [44]:
sqrt=lambda x,y:x+y
print(sqrt(2,4))

6

In [45]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")

In [46]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [47]:
my_list = [5, 10, 20, 10, 30]

my_list = [88 if x == 10 else x for x in my_list]

print(my_list)

[5, 88, 20, 88, 30]

In [48]:
dfz["Age"].apply(lambda age:age+55)

0    80
2    85
4    77
6    80
7    80
Name: Age, dtype: int64

In [49]:
df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")

0    Adult
1    Minor
2    Adult
3    Minor
4    Adult
5    Adult
6    Adult
7    Adult
8    Minor
Name: Age, dtype: object

In [50]:
dfu=df["Age"].apply(lambda x:x*2).copy()

In [51]:
dfu=df.dropna().copy()

In [52]:
dfu["Age_new"]=dfu["Age"].apply(lambda x:x*2)

In [53]:
dfu

,Name,Age,City,Gender,Email,Join Date,Age Group,Age_new
0,Alice,25.0,New York,F,alice@example.com,01-05-2021,Adult,50.0
2,Bob,30.0,Los Angeles,M,bob@example.com,15-06-2020,Adult,60.0
4,David,22.0,Mumbai,M,david@example.com,12-11-2019,Adult,44.0
6,Alice,25.0,New York,F,alice@example.com,01-05-2021,Adult,50.0
7,Alice,25.0,New York,F,alice@example.com,01-05-2021,Adult,50.0

In [54]:
update={'M':'Male','F':'Female'}
dfu["Gender"]=dfu["Gender"].map(update)

In [55]:
dfu

,Name,Age,City,Gender,Email,Join Date,Age Group,Age_new
0,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult,50.0
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,Adult,60.0
4,David,22.0,Mumbai,Male,david@example.com,12-11-2019,Adult,44.0
6,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult,50.0
7,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult,50.0

In [56]:
df["Gender"].map({
    "M": "Male",
    "F": "Female"
})

0    Female
1      Male
2      Male
3      Male
4      Male
5    Female
6    Female
7    Female
8      Male
Name: Gender, dtype: object

In [57]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [58]:
dfs=df.copy()

In [59]:
dfs.drop_duplicates()

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult

In [60]:

dfs["Gender"]=dfs["Gender"].map({"M":"Male","F":"Female"})

In [61]:
dfs.drop_duplicates()

      Name   Age         City  Gender              Email   Join Date Age Group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Adult

In [62]:
dfs["City"]=dfs["City"].replace({"Delhi":"Daroga khera","Mumbai":"Moazzam nagar"})

In [63]:
dfs

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
1,Charlie,NaN,Daroga khera,Male,charlie@example,20-07-2021,Minor
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,Adult
3,Charlie,NaN,Daroga khera,Male,charlie@example,20-07-2021,Minor
4,David,22.0,Moazzam nagar,Male,david@example.com,12-11-2019,Adult
5,NaN,28.0,Daroga khera,Female,eve@domain.com,NaN,Adult
6,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
7,Alice,25.0,New York,Female,alice@example.com,01-05-2021,Adult
8,Charlie,NaN,Daroga khera,Male,charlie@example,20-07-2021,Minor

## Data Transformation concept

In [64]:
df=pd.read_csv("Data_transformation.csv")

In [65]:
df

,Actors,Film,Year,Genre,Box office (USD),IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,839000000,8.8
1,Robert Downey Jr.,Iron Man,2008,Action,585000000,7.9
2,Tom Hanks,Forrest Gump,1994,Drama,678000000,8.8
3,Keanu Reeves,The Matrix,1999,Sci-Fi,467000000,8.7
4,Christian Bale,The Dark Knight,2008,Action,1006000000,9.0
5,Sam Worthington,Avatar,2009,Sci-Fi,2924000000,7.9
6,Matt Damon,The Martian,2015,Sci-Fi,630000000,8.0
7,Joaquin Phoenix,Joker,2019,Crime,1079000000,8.4
8,Chris Pratt,Guardians of the Galaxy,2014,Superhero,773000000,8.0
9,Margot Robbie,Barbie,2023,Comedy,1446000000,6.8

In [66]:
dfv=df.sort_values("Year")

In [67]:
dfv

,Actors,Film,Year,Genre,Box office (USD),IMDb
2,Tom Hanks,Forrest Gump,1994,Drama,678000000,8.8
3,Keanu Reeves,The Matrix,1999,Sci-Fi,467000000,8.7
1,Robert Downey Jr.,Iron Man,2008,Action,585000000,7.9
4,Christian Bale,The Dark Knight,2008,Action,1006000000,9.0
5,Sam Worthington,Avatar,2009,Sci-Fi,2924000000,7.9
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,839000000,8.8
8,Chris Pratt,Guardians of the Galaxy,2014,Superhero,773000000,8.0
6,Matt Damon,The Martian,2015,Sci-Fi,630000000,8.0
7,Joaquin Phoenix,Joker,2019,Crime,1079000000,8.4
9,Margot Robbie,Barbie,2023,Comedy,1446000000,6.8

In [68]:
df.sort_values("Year"
)
dfv.sort_values("Year",ascending=False) # for descending order and find the latest movies.

,Actors,Film,Year,Genre,Box office (USD),IMDb
9,Margot Robbie,Barbie,2023,Comedy,1446000000,6.8
7,Joaquin Phoenix,Joker,2019,Crime,1079000000,8.4
6,Matt Damon,The Martian,2015,Sci-Fi,630000000,8.0
8,Chris Pratt,Guardians of the Galaxy,2014,Superhero,773000000,8.0
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,839000000,8.8
5,Sam Worthington,Avatar,2009,Sci-Fi,2924000000,7.9
1,Robert Downey Jr.,Iron Man,2008,Action,585000000,7.9
4,Christian Bale,The Dark Knight,2008,Action,1006000000,9.0
3,Keanu Reeves,The Matrix,1999,Sci-Fi,467000000,8.7
2,Tom Hanks,Forrest Gump,1994,Drama,678000000,8.8

In [69]:
dfv.sort_values(["Year","IMDb"])

,Actors,Film,Year,Genre,Box office (USD),IMDb
2,Tom Hanks,Forrest Gump,1994,Drama,678000000,8.8
3,Keanu Reeves,The Matrix,1999,Sci-Fi,467000000,8.7
1,Robert Downey Jr.,Iron Man,2008,Action,585000000,7.9
4,Christian Bale,The Dark Knight,2008,Action,1006000000,9.0
5,Sam Worthington,Avatar,2009,Sci-Fi,2924000000,7.9
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,839000000,8.8
8,Chris Pratt,Guardians of the Galaxy,2014,Superhero,773000000,8.0
6,Matt Damon,The Martian,2015,Sci-Fi,630000000,8.0
7,Joaquin Phoenix,Joker,2019,Crime,1079000000,8.4
9,Margot Robbie,Barbie,2023,Comedy,1446000000,6.8

In [70]:
dfv
dfv.reset_index() # it does not change the original copy so to make change in original we us "inplace=True" 
dfv

,Actors,Film,Year,Genre,Box office (USD),IMDb
2,Tom Hanks,Forrest Gump,1994,Drama,678000000,8.8
3,Keanu Reeves,The Matrix,1999,Sci-Fi,467000000,8.7
1,Robert Downey Jr.,Iron Man,2008,Action,585000000,7.9
4,Christian Bale,The Dark Knight,2008,Action,1006000000,9.0
5,Sam Worthington,Avatar,2009,Sci-Fi,2924000000,7.9
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,839000000,8.8
8,Chris Pratt,Guardians of the Galaxy,2014,Superhero,773000000,8.0
6,Matt Damon,The Martian,2015,Sci-Fi,630000000,8.0
7,Joaquin Phoenix,Joker,2019,Crime,1079000000,8.4
9,Margot Robbie,Barbie,2023,Comedy,1446000000,6.8

In [71]:
dfv.reset_index(drop=True,inplace=True) # the original also had changes

In [72]:
dfv

,Actors,Film,Year,Genre,Box office (USD),IMDb
0,Tom Hanks,Forrest Gump,1994,Drama,678000000,8.8
1,Keanu Reeves,The Matrix,1999,Sci-Fi,467000000,8.7
2,Robert Downey Jr.,Iron Man,2008,Action,585000000,7.9
3,Christian Bale,The Dark Knight,2008,Action,1006000000,9.0
4,Sam Worthington,Avatar,2009,Sci-Fi,2924000000,7.9
5,Leonardo DiCaprio,Inception,2010,Sci-Fi,839000000,8.8
6,Chris Pratt,Guardians of the Galaxy,2014,Superhero,773000000,8.0
7,Matt Damon,The Martian,2015,Sci-Fi,630000000,8.0
8,Joaquin Phoenix,Joker,2019,Crime,1079000000,8.4
9,Margot Robbie,Barbie,2023,Comedy,1446000000,6.8

In [73]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)