In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("movies_data.xlsx")
df

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,836,8.8
1,Tom Hanks,Forrest Gump,1994,Drama,703,8.8
2,Christian Bale,The Dark Knight,2008,Action,914,9.0
3,Robert Downey Jr.,Iron Man,2008,Action,611,7.9
4,Sam Worthington,Avatar,2009,Sci-Fi,2435,7.9
5,Joaquin Phoenix,Joker,2019,Drama,778,8.3
6,Keanu Reeves,The Matrix,1999,Sci-Fi,501,8.7
7,Brad Pitt,Fight Club,1999,Drama,256,8.8
8,Matthew McConaughey,Interstellar,2014,Sci-Fi,731,8.7
9,Heath Ledger,The Dark Knight,2008,Action,914,9.0
10,Margot Robbie,Barbie,2023,Comedy,1195,6.8
11,Cillian Murphy,Oppenheimer,2023,Biography,830,8.6

In [3]:
# Question 1 to 5

df["Actor"]
df[["Film","Genre"]]
df.iloc[0:6]
df.loc[2:6,"Film"]
df[["Actor","Film","Genre"]].loc[0:5] # or more cleaner way :- df.loc[0:5,["Actor","Film","Genre"]]

               Actor             Film   Genre
0  Leonardo DiCaprio        Inception  Sci-Fi
1          Tom Hanks     Forrest Gump   Drama
2     Christian Bale  The Dark Knight  Action
3  Robert Downey Jr.         Iron Man  Action
4    Sam Worthington           Avatar  Sci-Fi
5    Joaquin Phoenix            Joker   Drama

In [4]:
# Question 6 to 10
# df.query("IMDb>8.5")
# df[df["BoxOffice (INR Crore)"]>800]["Film"] 
df.query("`BoxOffice (INR Crore)`>800")["Film"]
# df.loc[df["Year"]>2010,"Film"] # or df.query("Year>2010")[["Film"]]
# df.query("Genre == 'Sci-Fi'")
# df.query("IMDb>8.5")

0           Inception
2     The Dark Knight
4              Avatar
9     The Dark Knight
10             Barbie
11        Oppenheimer
Name: Film, dtype: object

In [5]:
#question 11 to 15
df.query("IMDb>8 and `BoxOffice (INR Crore)`>700")
df.query("Year >2010 and Genre=='Sci-Fi'")
df.query("IMDb>=8.5 or `BoxOffice (INR Crore)`>1000 ")
df.query("IMDb>8 and Genre=='Action'")
df.query("2000<Year<2020")

,Actor,Film,Year,Genre,BoxOffice (INR Crore),IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,836,8.8
2,Christian Bale,The Dark Knight,2008,Action,914,9.0
3,Robert Downey Jr.,Iron Man,2008,Action,611,7.9
4,Sam Worthington,Avatar,2009,Sci-Fi,2435,7.9
5,Joaquin Phoenix,Joker,2019,Drama,778,8.3
8,Matthew McConaughey,Interstellar,2014,Sci-Fi,731,8.7
9,Heath Ledger,The Dark Knight,2008,Action,914,9.0

In [9]:
#question 16 to 20...
df.loc[df["IMDb"].idxmax(),["Film","Actor","IMDb"]]
df.loc[df["IMDb"].idxmax(),["Film","Year","BoxOffice (INR Crore)"]]
# df.query("Actor=='Cillian Murphy' or Actor=='Leonardo DiCaprio'")["Film"]
# df.query("Year>2000 and IMDb>8 and `BoxOffice (INR Crore)`>700")["Film"]
# df.query("Genre=='Sci-Fi' and IMDb>=8.5")["Film"]

Film                     The Dark Knight
Year                                2008
BoxOffice (INR Crore)                914
Name: 2, dtype: object

In [8]:
import numpy as np
df1=np.argmax(df["IMDb"])
df1

np.int64(2)

In [14]:
# ques 1 to 4:-
df.query("IMDb>8.5")[["Film","Actor","IMDb"]]
df.query("Year>2010")[["Film","Year","Genre"]]
df.query("Genre=='Sci-Fi'")[["Film","Actor","IMDb"]]
df.query("`BoxOffice (INR Crore)`>800")[["Film","BoxOffice (INR Crore)"]]

               Film  BoxOffice (INR Crore)
0         Inception                    836
2   The Dark Knight                    914
4            Avatar                   2435
9   The Dark Knight                    914
10           Barbie                   1195
11      Oppenheimer                    830

In [18]:
# que 5 to 8:-
df.query("Year>2000 and IMDb>8")[["Film","Year","IMDb"]]
df.query("Genre=='Action' and IMDb>=8")[["Film","Actor","IMDb"]]

              Film           Actor  IMDb
2  The Dark Knight  Christian Bale   9.0
9  The Dark Knight    Heath Ledger   9.0